name: scorecard
on:
  branch_protection_rule:
  push:
    branches: [main]
  schedule:
    - cron: '0 5 * * 3'
  workflow_dispatch:
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  scorecard:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: NDDev-it-com/nddev-ci-workflows/.github/workflows/public-scorecard-json.yml@86f3e6d70a632561527379e5f962f57de81eb751 # 0.2.4
